MA-23950 clk: imx8mp: Fix build error
0d232fa3b076clk: imx8mp: inform CCF of maximum frequency of clocks
related changes are dropped when LINUX BSP merge, we keep it consistent
with LINUX BSP to avoid build error.

error log:

drivers/clk/imx/clk-imx8mp.c:572:13: error: unused function
'imx8mp_clocks_apply_constraints' [-Werror,-Wunused-function]

  572 | static void imx8mp_clocks_apply_constraints(const struct
      imx8mp_clock_constraints constraints[])

Change-Id: I15ed6d4f079e172b3f4e16a952437214ba2da393
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>