MA-16715-2 drm: cdns: Fix drm_mode_create_colorspace_property name
Below patch changed API name:
15dff3e222afc ("UPSTREAM: drm: Rename HDMI colorspace property creation function")

Modify driver accordingly to fix below build error:
drivers/gpu/drm/bridge/cadence/cdns-hdmi-core.c:390:8: error:
implicit declaration of function 'drm_mode_create_colorspace_property'

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Change-Id: I11ec284cc1da3cfa159d8d8811b7142e600b04d5