MA-24483-1 media: imx8-isi: fix const qualifier warning
Fix build error in imx8-isi-core.c due to incompatible pointer types:

drivers/media/platform/nxp/imx8-isi/imx8-isi-core.c:519:13: error:
assigning to 'struct mxc_isi_plat_data *' from 'const void *' discards qualifiers.

Change-Id: I6a4e551ee93b32cf64972b8714a05ec45aaf4866
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>