MA-22984 dma: pxp_dma_v3: Export symbol pxp_get_collision_info
The function pxp_get_collision_info is used by the mxc_epdc_v2_fb module
and needs to be exported.

error log:

ERROR: modpost: "pxp_get_collision_info" [drivers/video/fbdev/mxc/mxc_epdc_v2_fb.ko] undefined!

Change-Id: If90a0c93d294d5969ea276b7d97c2f1aa5454571
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>