MLK-10349 ARM: dts: imx6dql: fix the clock for MIPI CSI2
Fix the clock index for cfg clock and use MACRO instead of hard-codes.

This patch fixes the following issue.
-----------------------------------------------------------
root@imx6qdlsolo:~# /unit_tests/mxc_v4l2_capture.out -d /dev/video1 1.yuv
in_width = 176, in_height = 144
out_width = 176, out_height = 144
top = 0, left = 0
mipi csi2 can not receive sensor clk!
...

ERROR: v4l2 capture: mxc_v4l_dqueue timeout enc_counter 0
VIDIOC_DQBUF failed.ERROR: v4l2 capture: VIDIOC_QBUF: buffer already queued
-----------------------------------------------------------

Signed-off-by: Robby Cai <r63905@freescale.com>
(cherry picked from commit 6e4ee449de591d3cfb93575ca639ca32944832bc)