MLK-12392: arm: imx6q: fix lpddr2 build error if SMP is disabled
Fix build error if CONFIG_SMP is disabled:

arch/arm/mach-imx/busfreq_lpddr2.c: In function ‘update_lpddr2_freq_smp’:
arch/arm/mach-imx/busfreq_lpddr2.c:236:67: error: ‘me’ undeclared (first
use in this function)
  printk(KERN_DEBUG "Bus freq set to %d done! cpu=%d\n", ddr_rate, me);

Signed-off-by: Adrian Alonso <adrian.alonso@nxp.com>
Signed-off-by: Frank Li <Frank.Li@nxp.com>
(cherry picked from commit b185cd7a0220836338d9756c83337c05ab1cddac)