MA-10470 Support mfgtool defconfig build for android kernel
Fix below build error with arch/arm64/config/defconfig build
  mass_storage.c: In function 'msg_init':
  mass_storage.c:248:14: error: 'msg_registered' undeclared
    set_bit(0, &msg_registered);

Remove the msg_registered usage to align the commit below:
commit da785bb64fa661f5081b5c0351b798396b6071a6
Author: Alan Stern <stern@rowland.harvard.edu>
Date:   Thu Sep 21 13:22:00 2017 -0400

    USB: g_mass_storage: Fix deadlock when driver is unbound

Change-Id: I5a441aa5ab1206de725f438c848c3ba3c2c848e3
Signed-off-by: guoyin.chen <guoyin.chen@nxp.com>