MA-23351 sound: soc: fsl: Resolve recursive dependency between SND_SOC_FSL_MQS and IMX_SCMI_MISC_DRV
Merge the patch e385c781a305 firmware: arm_scmi: Fix i.MX build dependency

Resulted in the following build error:

error: recursive dependency detected!
        symbol SND_SOC_FSL_MQS depends on IMX_SCMI_MISC_DRV
        symbol IMX_SCMI_MISC_DRV is selected by SND_SOC_FSL_MQS

To resolve this, the conditional select IMX_SCMI_MISC_DRV statement in
SND_SOC_FSL_MQS is removed. The dependency on IMX_SCMI_MISC_DRV is
now handled solely through the depends on statement.

Change-Id: Ib77e985ef55ac4a4d92f5b0bf089e59eb217338f
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>