MA-10672[Android] Add select CLKSC_MMIO in Kconfig to avoid build error
The CONFIG_CLKSRC_MMIO is selected in BSP branch because of the config
CONFIG_ARCH_TEGRA. But this config is not exist in android defconfig.
It will cause following build error in android branch:
drivers/built-in.o: In function `sysctr_timer_init':
imx-scu-ocotp.c:(.init.text+0x298a4): undefined reference to `clocksource_mmio_init'

Change-Id: I546f329de0808cd827fbff9fd9a92663628bcbcf
Signed-off-by: Zhang Bo <bo.zhang@nxp.com>