MA-24190 media: ox05b1s: fix build error with C23 declaration rules
Fix build error in ox05b1s_mipi.c caused by C23 declaration rules.

The compiler reports an error when a label is followed directly by a
declaration, which is treated as a C23 extension:

drivers/media/i2c/ox05b1s/ox05b1s_mipi.c:737:3: error: label
followed by a declaration is a C23 extension [-Werror,-Wc23-extensions]
      737 |                 u32 long_exp = ctrl->val;

Change-Id: I41064245c5e3f20ade888578eab3f86db24d4141
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>