MA-24483-5 net: realtek: remove unused rtl8211f_disable_clk_out
Fix build error in realtek_main.c due to unused function :

common/drivers/net/phy/realtek/realtek_main.c:554:12: error:
unused function 'rtl8211f_disable_clk_out' [-Werror,-Wunused-function]

Change-Id: Ic3afb55d4b51c9f04aa47489d45fbc80f3cf34c3
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>