MA-24313 dma-buf: heaps: import DMA_BUF_HEAP namespace in dsp_heap
Fix build error in dsp_heap due to missing namespace import:

ERROR: modpost: module dsp_heap uses symbol dma_heap_add from namespace DMA_BUF_HEAP, but does not import it.
ERROR: modpost: module dsp_heap uses symbol dma_heap_get_drvdata from namespace DMA_BUF_HEAP, but does not import it.

Add MODULE_IMPORT_NS("DMA_BUF_HEAP") to resolve the build error.

Change-Id: I583fab7f8bc0959d7f225ea70a1a7e8382703dfb
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>