MA-24328 gpio: imx-scu: add missing MODULE_LICENSE
Add missing MODULE_LICENSE() to gpio-imx-scu.

Without MODULE_LICENSE(), modpost reports a build error:

    ERROR: modpost: missing MODULE_LICENSE() in drivers/gpio/gpio-imx-scu.o

Adding MODULE_LICENSE("GPL") resolves the issue.

Change-Id: I7b0972f1952c2ac2e3173533501b4362095dc913
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>